"""add clinics and schedules tables

Revision ID: 471651d5d50b
Revises: 33e0bb4bf1f2
Create Date: 2026-01-05 09:57:58.160825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '471651d5d50b'
down_revision: Union[str, Sequence[str], None] = '33e0bb4bf1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_id'), 'clinics', ['id'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_schedules_id'), 'doctor_schedules', ['id'], unique=False)
    op.add_column('appointments', sa.Column('clinic_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('appointments', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('appointments', 'appointment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.drop_constraint(op.f('appointments_patient_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_doctor_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'clinics', ['clinic_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.add_column('doctors', sa.Column('clinic_id', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('doctors', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('doctors', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('doctors', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('doctors', 'specialty',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_unique_constraint(None, 'doctors', ['email'])
    op.create_foreign_key(None, 'doctors', 'clinics', ['clinic_id'], ['id'], ondelete='SET NULL')
    op.add_column('patients', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('patients', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('patients_phone_key'), 'patients', type_='unique')
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=True)
    op.create_unique_constraint(None, 'patients', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.create_unique_constraint(op.f('patients_phone_key'), 'patients', ['phone'], postgresql_nulls_not_distinct=False)
    op.alter_column('patients', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('patients', 'created_at')
    op.drop_column('patients', 'date_of_birth')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.alter_column('doctors', 'specialty',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('doctors', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('doctors', 'is_active')
    op.drop_column('doctors', 'email')
    op.drop_column('doctors', 'phone')
    op.drop_column('doctors', 'clinic_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_doctor_id_fkey'), 'appointments', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key(op.f('appointments_patient_id_fkey'), 'appointments', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.alter_column('appointments', 'appointment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('appointments', 'created_at')
    op.drop_column('appointments', 'notes')
    op.drop_column('appointments', 'status')
    op.drop_column('appointments', 'clinic_id')
    op.drop_index(op.f('ix_doctor_schedules_id'), table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    op.drop_index(op.f('ix_clinics_id'), table_name='clinics')
    op.drop_table('clinics')
    # ### end Alembic commands ###
